import express from "express";
import { getStudentAttendanceReport, getLectureAttendanceSummary, getFacultyDashboardStats } from "../../controllers/report/report.controller.js";
import protect from "../../middleware/auth.middleware.js";
import authorizeRoles from "../../middleware/role.middleware.js";
import getProfileId from "../../middleware/identity.middleware.js";
const r = express.Router();
r.get("/api/report/student/my-attendance", protect, getProfileId, authorizeRoles("STUDENT"), getStudentAttendanceReport);
r.get("/api/report/lecture/:lectureSessionId/summary", protect, authorizeRoles("FACULTY","ADMIN"), getLectureAttendanceSummary);
r.get("/api/report/faculty/dashboard", protect, getProfileId, authorizeRoles("FACULTY","ADMIN"), getFacultyDashboardStats);
export default r;
