import express from "express";
import { createSubject, getAllSubjects, updateSubject, deleteSubject, permanentlyDeleteSubject } from "../../controllers/academics/subject.controller.js";
import protect from "../../middleware/auth.middleware.js";
import authorizeRoles from "../../middleware/role.middleware.js";
const r = express.Router();
r.post("/subject/create", protect, authorizeRoles("ADMIN"), createSubject);
r.get("/subjects", getAllSubjects);
r.put("/subject/:id", protect, authorizeRoles("ADMIN"), updateSubject);
r.delete("/subject/:id", protect, authorizeRoles("ADMIN"), deleteSubject);
r.delete("/subject/:id/permanent", protect, authorizeRoles("ADMIN"), permanentlyDeleteSubject);
export default r;
